## Customize these as needed
title: SDG Translations
description: >-
  A project to compile and translate text related to the United Nation's
  Sustainable Development Goals, and then provide those translations as JSON.
#baseurl: "/sdg-translations"
#url: "https://open-sdg.github.io"
#repo: "https://github.com/open-sdg/sdg-translations"

baseurl: "/IM_translations"
url: "https://wohnungnds.github.io"
repo: "https://github.com/wohnungnds/IM_translations"




# Build settings
markdown: kramdown
source: www
theme: jekyll-theme-cayman

# Python scripts build these files, so tell Jekyll not to process them
keep_files:
  - "*.json"
  - "*.csv"
